# Generated by Django 4.1.2 on 2022-11-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(help_text='This field is required', max_length=200)),
                ('status', models.CharField(choices=[('TR', 'TO READ'), ('CR', 'CURRENTLY READING'), ('FR', 'FINISHED READING')], default='TR', max_length=100)),
            ],
        ),
    ]
